In [5]:
import pandas as pd
import numpy as np
import re

In [6]:
file_path = "C:/Users/HP/Desktop/CA2 ML/tweets.csv"

# Read the CSV file using pandas
try:
    df = pd.read_csv(file_path, encoding='latin1', sep='\t', quoting=1)  # Use sep='\t' for tab separation
except Exception as e:
    print(f"Error reading file: {e}")
# Remove leading and trailing whitespaces from all columns
df = df.apply(lambda x: x.str.strip() if x.dtype == "object" else x)

# Print the DataFrame
df.sample(10)


id               keyword                        location  \
3181    3181                deaths                       Hong Kong   
8235    8235            quarantine                             NaN   
3234    3234                deaths           Wherever I Lay My Hat   
7899    7899          obliteration                      Tyrone, GA   
5676    5676    first%20responders                  Long Beach, CA   
10125  10125                threat                             NaN   
2188    2188  chemical%20emergency                  Lagos, Nigeria   
8749    8749               rioting                             NaN   
3115    3115                 death  Stuffed In The Corner, YouTube   
9929    9929             survivors                 Llanelli, Wales   

                                                    text  target  
3181   CCP is mimicking Nazi's evil acts, but still t...       0  
8235   January 14, 2020 at about 08:30 am, personnel ...       0  
3234   And responsible for deaths of a million Iraq s...       0  
7899   I must not fear. Fear is the mind-killer. Fear...       0  
5676   I’m going with my job for a weekend event. The...       0  
10125  In today's I write about the threat #FacialRec...       0  
2188   This man was seen fallen down in our community...       1  
8749   Where are the tweets from October about people...       0  
3115   #NinjaTribes Official Awakenings for Shippuden...       0  
9929   Great call by ?? supporting paid leave for sur...       0

In [7]:
df2=pd.read_csv("C:/Users/HP/Desktop/CA2 ML/tweets2.csv")
df2

id keyword location  \
0         1     NaN      NaN   
1         4     NaN      NaN   
2         5     NaN      NaN   
3         6     NaN      NaN   
4         7     NaN      NaN   
...     ...     ...      ...   
7608  10869     NaN      NaN   
7609  10870     NaN      NaN   
7610  10871     NaN      NaN   
7611  10872     NaN      NaN   
7612  10873     NaN      NaN   

                                                   text  target  
0     Our Deeds are the Reason of this #earthquake M...       1  
1                Forest fire near La Ronge Sask. Canada       1  
2     All residents asked to 'shelter in place' are ...       1  
3     13,000 people receive #wildfires evacuation or...       1  
4     Just got sent this photo from Ruby #Alaska as ...       1  
...                                                 ...     ...  
7608  Two giant cranes holding a bridge collapse int...       1  
7609  @aria_ahrary @TheTawniest The out of control w...       1  
7610  M1.94 [01:04 UTC]?5km S of Volcano Hawaii. htt...       1  
7611  Police investigating after an e-bike collided ...       1  
7612  The Latest: More Homes Razed by Northern Calif...       1  

[7613 rows x 5 columns]

In [8]:
df = pd.concat([df, df2], ignore_index=True)

In [9]:
df.shape

(18983, 5)

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18983 entries, 0 to 18982
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   id        18983 non-null  int64 
 1   keyword   18922 non-null  object
 2   location  13032 non-null  object
 3   text      18983 non-null  object
 4   target    18983 non-null  int64 
dtypes: int64(2), object(3)
memory usage: 741.6+ KB


In [11]:
df['target'].value_counts()

target
0    13598
1     5385
Name: count, dtype: int64

## Data cleaning

In [12]:
keyword=df['keyword'].value_counts()
keyword.head(20)

keyword
thunderstorm     126
flattened        122
fear             120
fatalities       119
mass%20murder    119
stretcher        119
engulfed         118
deluge           118
derailment       118
drowning         117
collision        116
drown            115
deaths           114
derailed         114
sunk             113
damage           113
sirens           112
obliterate       111
body%20bags      110
attack           110
Name: count, dtype: int64

In [13]:
pattern = r'[^a-zA-Z\s,]'

# Clean the 'location' column
df['keyword'] = df['keyword'].str.replace(pattern, '', regex=True)

In [14]:
print(df['keyword'].isnull().sum())


61


In [15]:
df['keyword'] = df['keyword'].fillna('empty')  # Fill NaN with an empty string


In [16]:
import urllib.parse
df['keyword'] = df['keyword'].apply(urllib.parse.unquote)
df[['keyword']].value_counts().head(20)

keyword     
thunderstorm    126
flattened       122
fear            120
massmurder      119
fatalities      119
stretcher       119
engulfed        118
deluge          118
derailment      118
drowning        117
collision       116
drown           115
deaths          114
derailed        114
sunk            113
damage          113
sirens          112
obliterate      111
bodybags        110
attack          110
Name: count, dtype: int64

In [17]:
import nltk
nltk.download('wordnet')  # For lemmatization
nltk.download('punkt')     # For tokenization


[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\HP\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\HP\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [18]:
from nltk.stem import WordNetLemmatizer
from nltk.tokenize import word_tokenize
lemmatizer = WordNetLemmatizer()

# Function to lemmatize words in the keyword column
def lemmatize_keywords(keywords):
    tokens = word_tokenize(keywords)
    lemmatized = [lemmatizer.lemmatize(token) for token in tokens]
    return ' '.join(lemmatized)

# Apply lemmatization to the keyword column
df['keyword'] = df['keyword'].apply(lemmatize_keywords)
df['keyword'].value_counts().head(20)

keyword
death           221
fatality        210
weapon          207
hostage         205
injury          183
casualty        172
flood           172
siren           162
wildfire        156
thunderstorm    126
flattened       122
fear            120
stretcher       119
massmurder      119
engulfed        118
derailment      118
deluge          118
drowning        117
collision       116
drown           115
Name: count, dtype: int64

In [19]:

keyword_mapping = {
    'collide': 'collision',
    'collided': 'collision',
    'crashed': 'crash',
    'crushed':'crush',
    'bioterror':'bioterrorism',
    'demolished':'demolition',
    'demolish':'demolition',
    'derail':'derailment',
    'derailed':'derailment',
    'desolate':'desolation',
    'destroy':"destruction",
    'destroyed':'destruction',
    'bloody':'blood',
    'devastated':'devastation',
    'drowned':'drown',
    'drowning':'drown',
    'deluged':'deluge',
    'emergency':'emergency service',
    'emergency plan':'emergency service',
    'evacuate':'evacuation',
    'evacuated':'evacuation',
    'explode':'explosion',
    'exploded':'explosion',
    'fatal':'fatality',
    'flooding':'flood',
    'hail':'hailstorm',
    'hazard':'hazardous',
    'hijacker':'hijack',
    'hijacking':'hijack',
    'injured':'injury',
    'inundated':'inundation',
    'mass murderer':'mass murder',
    'obliterated':'obliteration',
    'obliterate':'obliteration',
    'panicking':'panic',
    'quarantined':'quarantine',
    'rescuer':'rescue',
    'rescued':'rescue',
    'rioting':'riot',
    'screaming':'scream',
    'screamed':'scream',
    'sinking':'sink',
    'sinkhole':'sink',
    'sunk':'sink',
    'storm':'snowstorm',
    'suicide bombing':'suicide bomb',
    'suicide bomber':'suicide bomb',
    'survivor':'survive',
    'survived':'survive',
    'terrorist':'terrorism',
    'thunder':'thunderstorm',
    'trapped':'trap',
    'traumatised':'trauma',
    'wild fire':'wildfire',
    'wounded':'wound',
    'wreck':'wreckage',
    'wrecked':'wreckage',
    'annihilated':'annihilation',
    'arsonist':'arson',
    'attacked':'attack',
    'blazing':'blaze',
    'bleeding':'blood',
    'bloody':'blood',
    'body bagging':'body bag',
    'bombed':'bomb',
    'bombing':'bomb',
    'building burning':'building on fire',
    'burned':'burn',
    'burning':'burn',
    'catastrophic':'catastrophe',
    'collapsed':'collapse',
    'dead':'death',
    'electrocuted':'electrocute',
    'blown up':'blew up',
    'radiationemergency':'radiation emergency',
    'burningbuildings':'burning buildings'
   
}

df['keyword'] = df['keyword'].replace(keyword_mapping)
df['keyword'].value_counts()
#print(df['keyword'].unique())

keyword
derailment             329
drown                  329
collision              315
death                  311
blood                  296
                      ... 
rainstorm               45
radiation emergency     41
tsunami                 40
burning buildings       37
detonation              32
Name: count, Length: 152, dtype: int64

In [20]:
df['location']=df['location'].str.strip()

In [21]:
pattern = r'[^a-zA-Z\s,]'
df['location'] = df['location'].str.replace(pattern, '', regex=True)


In [22]:
df['location']=df['location'].str.title()
df['location']=df['location'].str.strip()

In [23]:
df['location'].value_counts().head(30)

location
                           299
Usa                        169
United States              151
London                     124
Uk                         115
India                      106
Australia                  105
London, England             92
New York                    88
Los Angeles, Ca             75
United Kingdom              73
Nigeria                     71
Canada                      66
California, Usa             62
Worldwide                   59
Washington, Dc              56
Earth                       52
Chicago, Il                 47
Lagos, Nigeria              43
Ireland                     43
England, United Kingdom     42
South Africa                38
Atlanta, Ga                 38
Mumbai                      38
New York, Ny                37
Everywhere                  34
Melbourne, Victoria         34
Sydney                      33
,                           33
Kenya                       33
Name: count, dtype: int64

In [24]:
location_mapping={
    'Usa':'United States',
    'Uk':"United Kingdom",
    'Bharat':'India',
    'Earth':'Unknown',
    'Everywhere':'Unknown',
    'Home':'Unknown',
    ',':'Unknown',
    'Worldwide':'Unknown',
    'England':'United Kingdom',
    'In this world':'Unknown',
    'Us':'United States',
    'Male':'Unknown',
    'City of gold':'Dubai',
    'In your head':'Unknown',
    'Sheher':'Unknown',
    'Mxico':'Mexico',
    'Ot Or Nothing':'Unknown',
    'In Your Heart':'Unknown',
    'Hell':'Unknown',
    'Httpsjereneroseweeblycom':'Unknown',
    'In My Own Dreams':'Unknown'

}
df['location'] = df['location'].replace(location_mapping)

In [25]:
# Clean the location column and fill NaN with 'Unknown'
df['cleaned_location'] = (
    df['location']
    .replace(['', np.nan], np.nan)  # Replace empty strings with NaN
    .str.replace(r'[^a-zA-Z\s,]', '', regex=True)  # Remove special characters
    .str.strip()  # Remove leading and trailing whitespace
)

df.drop('cleaned_location',axis=1,inplace=True)

df['location'] = df['location'].replace("", pd.NA)
df.loc[(df['location'].str.len() > 25) | (df['location'].str.len() == 1) , 'location'] = 'Unknown'

# After cleaning, fill NaN values
df['location'] = df['location'].fillna("Unknown")
df['location'] = df['location'].str.replace(r'\s+', ' ', regex=True).str.strip()

In [26]:
df['location'].value_counts().head(20)

location
Unknown                    7341
United States               335
United Kingdom              211
London                      124
India                       110
Australia                   105
London, England              92
New York                     88
Los Angeles, Ca              75
Nigeria                      71
Canada                       66
California, Usa              62
Washington, Dc               56
Chicago, Il                  47
Lagos, Nigeria               43
Ireland                      43
England, United Kingdom      42
Atlanta, Ga                  38
Mumbai                       38
South Africa                 38
Name: count, dtype: int64

## Text preprocessing

In [27]:
pattern = r'[^a-zA-Z0-9\s,.#]'

# Clean the 'location' column
df['text'] = df['text'].str.replace(pattern, '', regex=True)

In [28]:

def remove_links(text):
    return re.sub(r'http\S+|www\S+|https\S+', '', text, flags=re.MULTILINE)
df['text'] = df['text'].apply(remove_links)


# Strip leading and trailing whitespace
df['text'] = df['text'].str.strip()

In [29]:
df.drop("id",axis=1,inplace = True)

In [30]:
import tensorflow as tf

In [31]:
X=df.drop('target',axis=1)
y=df['target']

In [32]:
messages=X.copy()
voc_size=8000

In [33]:
import re
from nltk.corpus import stopwords
nltk.download('stopwords')

corpus = []
for i in range(0, len(messages)):
    review = re.sub('[^a-zA-Z]', ' ', messages['text'][i])
    review = review.lower()
    review = review.split()

    review = [lemmatizer.lemmatize(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

def remove_all_single_chars(text):
    return re.sub(r'\b\w\b', '', text)

# Apply the function to the corpus and also remove extra spaces
corpus = [re.sub(r'\s+', ' ', remove_all_single_chars(sentence)).strip() for sentence in corpus]



[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\HP\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [34]:
corpus

['communal violence bhainsa telangana stone pelted muslim house house vehicle set ablaze',
 'telangana section imposed bhainsa january clash erupted two group january po',
 'arsonist set car ablaze dealership',
 'arsonist set car ablaze dealership',
 'lord jesus love brings freedom pardon fill holy spirit set heart ablaze',
 'child chinese tweet would gone viral social medium would ablaze snl would made racist',
 'several house set ablaze ngemsibaa village oku sub division north west region cameroon',
 'asansol bjp office salanpur village set ablaze last night bjp alleged tmc behind incident police',
 'national security minister kan dapaahs side chic set internet ablaze latest powerful video',
 'creature who soul longer clarent blue ablaze thing carrying memory memory',
 'image showing havoc caused cameroon military torched house oku shameless military reported',
 'social medium went banana chuba hubbard announced monday evening plan return okstate',
 'hausa youth set area office apapa

## Sentiment analysis

In [35]:
from textblob import TextBlob

def get_sentiment(text):
    blob = TextBlob(text)
    polarity = blob.sentiment.polarity
    return 'positive' if polarity > 0 else 'negative' if polarity < 0 else 'neutral'

df['predicted_sentiment'] = df['text'].apply(get_sentiment)



In [36]:
# Display the results
df[['text', 'predicted_sentiment']]

text predicted_sentiment
0      Communal violence in Bhainsa, Telangana. Stone...             neutral
1      Telangana Section 144 has been imposed in Bhai...             neutral
2                Arsonist sets cars ablaze at dealership             neutral
3                Arsonist sets cars ablaze at dealership             neutral
4      Lord Jesus, your love brings freedom and pardo...            positive
...                                                  ...                 ...
18978  Two giant cranes holding a bridge collapse int...             neutral
18979  ariaahrary TheTawniest The out of control wild...            positive
18980             M1.94 0104 UTC5km S of Volcano Hawaii.             neutral
18981  Police investigating after an ebike collided w...            negative
18982  The Latest More Homes Razed by Northern Califo...            positive

[18983 rows x 2 columns]

## Topic modelling for theme extraction

In [37]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.decomposition import LatentDirichletAllocation


In [38]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf_vectorizer = TfidfVectorizer()
tfidf_matrix = tfidf_vectorizer.fit_transform(corpus)

lda = LatentDirichletAllocation(n_components=20, random_state=42)
lda.fit(tfidf_matrix)

terms = tfidf_vectorizer.get_feature_names_out()
for index, topic in enumerate(lda.components_):
    print(f"Topic {index + 1}:")
    print([terms[i] for i in topic.argsort()[-12:]])

Topic 1:
['drowning', 'costlier', 'refugio', 'battle', 'lvl', 'backup', 'projected', 'id', 'bigger', 'like', 'spill', 'oil']
Topic 2:
['got', 'year', 'japan', 'detonate', 'anniversary', 'pick', 'like', 'im', 'hiroshima', 'hell', 'bomb', 'atomic']
Topic 3:
['australia', 'fuck', 'get', 'building', 'people', 'change', 'forest', 'death', 'like', 'one', 'wild', 'fire']
Topic 4:
['electrocute', 'abc', 'siren', 'like', 'northern', 'latest', 'home', 'screaming', 'razed', 'california', 'wildfire', 'im']
Topic 5:
['evacuated', 'rescue', 'set', 'iran', 'sue', 'disease', 'fire', 'affected', 'fatal', 'outbreak', 'legionnaire', 'family']
Topic 6:
['eyewitness', 'need', 'record', 'found', 'new', 'crushed', 'news', 'time', 'drought', 'light', 'wave', 'heat']
Topic 7:
['demolish', 'market', 'im', 'brace', 'triumphant', 'gove', 'school', 'upheaval', 'five', 'year', 'heart', 'party']
Topic 8:
['flood', 'disaster', 'like', 'amp', 'nuclear', 'get', 'airport', 'watch', 'minute', 'swallowed', 'sandstorm', 'h

In [39]:
topic_distribution = lda.transform(tfidf_matrix)
dominant_topic = np.argmax(topic_distribution, axis=1)

df2 = pd.DataFrame({'text': corpus, 'dominant_topic': dominant_topic})

topic_names = {
    1: "Environmental Disasters and Oil Spills",
    2: "Atomic Bombing and Hiroshima",
    3: "Australian Wildfires and Climate Change",
    4: "Ablaze and Emergency Response",
    5: "Evacuations and Disease Outbreaks",
    6: "Natural Disasters and Heat Waves",
    7: "Political and Social Upheaval",
    8: "Floods and Sandstorms",
    9: "Severe Storms and Infrastructure Collapse",
    10: "Severe Weather Alerts",
    11: "Train Accidents and Derailments",
    12: "Earthquakes and Aftershocks",
    13: "Fires and Fatalities",
    14: "Plane Crash and Malaysian Airlines MH370",
    15: "Natural Disasters and Tornadoes",
    16: "Rescue and Migrant Crisis",
    17: "Transportation Accidents and Structural Failures",
    18: "Urban Violence and Drunk Driving",
    19: "Volcano Eruptions and Natural Hazards",
    20: "Terrorism and Bombings"
}


df2['topic_name'] = df2['dominant_topic'].map(topic_names)


In [40]:
df2

text  dominant_topic  \
0      communal violence bhainsa telangana stone pelt...               7   
1      telangana section imposed bhainsa january clas...               5   
2                     arsonist set car ablaze dealership               4   
3                     arsonist set car ablaze dealership               4   
4      lord jesus love brings freedom pardon fill hol...              12   
...                                                  ...             ...   
18978  two giant crane holding bridge collapse nearby...               8   
18979  ariaahrary thetawniest control wild fire calif...               4   
18980                              utc km volcano hawaii              16   
18981  police investigating ebike collided car little...               1   
18982  latest home razed northern california wildfire...               3   

                                    topic_name  
0                Political and Social Upheaval  
1            Evacuations and Disease Outbreaks  
2                Ablaze and Emergency Response  
3                Ablaze and Emergency Response  
4                  Earthquakes and Aftershocks  
...                                        ...  
18978                    Floods and Sandstorms  
18979            Ablaze and Emergency Response  
18980                Rescue and Migrant Crisis  
18981   Environmental Disasters and Oil Spills  
18982  Australian Wildfires and Climate Change  

[18983 rows x 3 columns]

## Training the model


As we have sentiment as target variable here having value 0 and 1 so now we are trying to train the model using word embeddings first to convert the text to vectors then we can svm or random forest to classify the sentiment

## Word embeddings

In [41]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [42]:
### Vocabulary size
voc_size=5000
from tensorflow.keras.preprocessing.text import one_hot
onehot_repr=[one_hot(words,voc_size)for words in corpus]
onehot_repr

[[438, 1987, 3725, 603, 3561, 2635, 4649, 4375, 4375, 1456, 2435, 3772],
 [603, 916, 629, 3725, 964, 2515, 4179, 754, 1772, 964, 1760],
 [3879, 2435, 3668, 3772, 2519],
 [3879, 2435, 3668, 3772, 2519],
 [4845, 3626, 472, 4905, 1402, 4734, 1020, 1873, 3055, 2435, 535, 3772],
 [2310,
  3904,
  4078,
  3318,
  1997,
  399,
  4221,
  2487,
  3318,
  3772,
  5,
  3318,
  3712,
  2268],
 [4047, 4375, 2435, 3772, 487, 3712, 3352, 2832, 3878, 3627, 4643, 3146, 1902],
 [1275,
  4575,
  4067,
  1592,
  3712,
  2435,
  3772,
  3749,
  4677,
  4575,
  2280,
  1809,
  4503,
  1306,
  4262],
 [3036, 693, 3573, 2059, 4801, 3702, 4450, 2435, 3300, 3772, 4297, 1668, 603],
 [2990, 4437, 299, 4619, 1884, 520, 3772, 948, 4749, 1919, 1919],
 [41, 295, 2668, 4373, 1902, 795, 1906, 4375, 3352, 1460, 795, 805],
 [4221, 2487, 719, 1384, 1437, 1682, 3072, 2803, 3256, 1499, 2892, 817],
 [1552,
  3484,
  2435,
  4412,
  4067,
  3555,
  1821,
  444,
  1275,
  4412,
  3772,
  967,
  3851,
  677,
  3989,
  4412,
  4

In [43]:
## Get the Independent Features
X=df.drop('target',axis=1)
## Get the Dependent features
y=df['target']

In [45]:
sent_length=20
embedded_docs=pad_sequences(onehot_repr,padding='post',maxlen=sent_length)
print(embedded_docs)

[[ 438 1987 3725 ...    0    0    0]
 [ 603  916  629 ...    0    0    0]
 [3879 2435 3668 ...    0    0    0]
 ...
 [1484 2674 1481 ...    0    0    0]
 [4262 3131 3964 ...    0    0    0]
 [4297 1051 2507 ...    0    0    0]]


In [46]:
embedded_docs[1]

array([ 603,  916,  629, 3725,  964, 2515, 4179,  754, 1772,  964, 1760,
          0,    0,    0,    0,    0,    0,    0,    0,    0])

In [48]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

In [ ]:
from tensorflow.keras.layers import Dropout
## Creating model
embedding_vector_features=40 ##features representation (dim)
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(Dropout(0.3))
model.add(LSTM(100))
model.add(Dropout(0.3))
model.add(Dense(1,activation='sigmoid')) # as sp is binary
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

In [70]:
len(embedded_docs),y.shape

(18983, (18983,))

In [ ]:
X_final=np.array(embedded_docs)
y_final=np.array(y)

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.33, random_state=42)

In [ ]:
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=5,batch_size=64)

Epoch 1/5
199/199 [==============================] - 8s 39ms/step - loss: 0.1528 - accuracy: 0.9398 - val_loss: 0.6858 - val_accuracy: 0.7925
Epoch 2/5
199/199 [==============================] - 7s 35ms/step - loss: 0.1428 - accuracy: 0.9411 - val_loss: 0.7373 - val_accuracy: 0.7887
Epoch 3/5
199/199 [==============================] - 7s 35ms/step - loss: 0.1319 - accuracy: 0.9486 - val_loss: 0.7185 - val_accuracy: 0.7848
Epoch 4/5
199/199 [==============================] - 6s 30ms/step - loss: 0.1199 - accuracy: 0.9539 - val_loss: 0.9496 - val_accuracy: 0.7832
Epoch 5/5
199/199 [==============================] - 6s 29ms/step - loss: 0.1031 - accuracy: 0.9592 - val_loss: 0.9383 - val_accuracy: 0.7820


In [71]:
y_pred=model.predict(X_test)

196/196 [==============================] - 1s 6ms/step


In [72]:
y_pred=np.where(y_pred > 0.6, 1,0) ##AUC ROC Curve

In [73]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred)

array([[3923,  556],
       [ 770, 1016]], dtype=int64)

In [74]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.7883479648842777

In [75]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.84      0.88      0.86      4479
           1       0.65      0.57      0.61      1786

    accuracy                           0.79      6265
   macro avg       0.74      0.72      0.73      6265
weighted avg       0.78      0.79      0.78      6265

